### PR TITLE
Update runtime to 20.08

### PR DESCRIPTION
**Pull request by AsciiWolf**
/cc @bilelmoussaoui

### CODE REVIEW

**Comment by AsciiWolf** [comment]
`/bin/sh: line 1:   685 Segmentation fault      ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>'`

Interesting...

**Comment by AsciiWolf** [comment]
@bilelmoussaoui Seems to work fine, feel free to merge.

**Comment by AsciiWolf** [comment]
@bilelmoussaoui Let me know if there are any issues.

**Comment by cho2** [comment]
cc @flathub/reviewers

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Let me know if there are any issues.

The only issue so far is time

**Pull request merged**
